INSERT INTO Service (Name) VALUES ('Test: Varnish port 80 | Services: DrVideo applications + VTC | Location: Availo');
INSERT INTO Service (Name) VALUES ('Test: Apache port 8080 | Services: DrVideo applications + VTC | Location: Availo');
INSERT INTO Service (Name) VALUES ('DrVideo Encoding');
INSERT INTO Service (Name) VALUES ('Test: Apache port 80 | Services: DrFront + custom apps | Location: Availo');
INSERT INTO Service (Name) VALUES ('Test: ICMP ping | Services: DrVideo Storage + FTP Server | Location: Availo');
INSERT INTO Service (Name) VALUES ('Test: ICMP Ping | Service: MySQL | Location: Availo');
INSERT INTO Service (Name) VALUES ('Test: ICMP Ping Switch #1 | Service: Internal network | Location: A55');
INSERT INTO Service (Name) VALUES ('Test: ICMP Ping | Load balancer gateway for all services | Location: Availo, M323');
INSERT INTO Service (Name) VALUES ('Test: ICMP Ping | Services: Office Network Gateway | Location A55, Fasthost');
INSERT INTO Service (Name) VALUES ('Test: Varnish port 80 | Services: SeByen API feed (sebyen.drvideo.aptoma.no/api/?do=feed) | Location: Availo');
INSERT INTO Service (Name) VALUES ('Test: Varnish port 80 | Services: SeByen data feed (sebyen.drvideo.aptoma.no/data/actions/videolist/) | Location: Availo');
INSERT INTO Service (Name) VALUES ('Test: HTTP Port 443 | Services: Chef APIs | Location: Opscode Hosted Chef');
INSERT INTO Service (Name) VALUES ('Test: HTTP Port 443 | Services: Chef Control Panel | Location: Opscode Hosted Chef');
INSERT INTO Service (Name) VALUES ('Test: Apache port 80 | Services: DrFront | Location: Rackspace MSL');
INSERT INTO Service (Name) VALUES ('Test: ICMP Ping | Service: Compserver 08 | Location: A55');
INSERT INTO Service (Name) VALUES ('Test: ICMP Ping | Service: Compserver 07 | Location: A55');
INSERT INTO Service (Name) VALUES ('Test: ICMP Ping | Service: Compserver 06 | Location: A55');
INSERT INTO Service (Name) VALUES ('Test: ICMP ping | Services: Nagios | Location: Rackspace LON');
INSERT INTO Service (Name) VALUES ('Test: ICMP Ping | Service: DrFront Access Proxy | Location: Rackspace LON');
INSERT INTO Service (Name) VALUES ('Test: ICMP Ping | Service: Munin | Location: Rackspace LON');
INSERT INTO Service (Name) VALUES ('Test: Apache port 80 at DrPublish API, through Varnish and LB | Services: Aftenposten DrPublish API | Location: Softlayer AMS');
INSERT INTO Service (Name) VALUES ('Test: ICMP Ping - Services: DrFront - Location: Rackspace');
INSERT INTO Service (Name) VALUES ('Test: ICMP Ping | Service: DrFront MySQL | Location: Rackspace UK');
INSERT INTO Service (Name) VALUES ('DrFront Backoffice');
INSERT INTO Service (Name) VALUES ('DrVideo Backoffice');
INSERT INTO Service (Name) VALUES ('DrVideo CDN');
INSERT INTO Service (Name) VALUES ('DrVideo API');
INSERT INTO Service (Name) VALUES ('Pingdom Status Panel Self-test');
INSERT INTO Service (Name) VALUES ('Test: ICMP Ping - custom-apps-01.ams.aptoma.no - Location: AMS');
INSERT INTO Service (Name) VALUES ('Test: ICMP Ping - drp-backoffice-01.ams.aptoma.no - Location: AMS');
INSERT INTO Service (Name) VALUES ('Test: ICMP Ping - drp-mysql-01.ams.aptoma.no - Location: AMS');
INSERT INTO Service (Name) VALUES ('Test: ICMP Ping - drp-rai-01.ams.aptoma.no - Location: AMS');
INSERT INTO Service (Name) VALUES ('Test: ICMP Ping - drp-solr-01.ams.aptoma.no  - Location: AMS');
INSERT INTO Service (Name) VALUES ('Test: ICMP Ping - irc.ams.aptoma.no - Location: AMS');
INSERT INTO Service (Name) VALUES ('Test: ICMP Ping - munin.ams.aptoma.no - Location: AMS');
INSERT INTO Service (Name) VALUES ('Test: ICMP Ping - nagios.ams.aptoma.no - Location: AMS');
INSERT INTO Service (Name) VALUES ('Test: ICMP Ping - varnish-01.ams.aptoma.no - Location: AMS');
INSERT INTO Service (Name) VALUES ('Test: ICMP Ping - lb-http-01.ams.aptoma.no - Location: AMS');
INSERT INTO Service (Name) VALUES ('Test: DrPublish HTTP RAI API via Load balancer and Varnish - Services: UiN DrPublish - Location: Amsterdam');
INSERT INTO Service (Name) VALUES ('Test: DrPublish HTTP RAI API via Load balancer and Varnish - Services: HiVolda DrPublish API - Location: Amsterdam');
INSERT INTO Service (Name) VALUES ('DrPublish Backoffice');
INSERT INTO Service (Name) VALUES ('DrPublish API');
INSERT INTO Service (Name) VALUES ('Test: TCP Connect port 80 - lb-http-01.ams.aptoma.no - Location: AMS');
INSERT INTO Service (Name) VALUES ('Test: HTTP Port 80 - lb-http-01.ams.aptoma.no - Location: AMS');
INSERT INTO Service (Name) VALUES ('Test: ICMP Ping - varnish-01.ams.aptoma.no - Location: AMS');
INSERT INTO Service (Name) VALUES ('Test: Apache port 80 - DrVideo Admin Prod - Amsterdam');
INSERT INTO Service (Name) VALUES ('Test: Valid HTTPS DrVideo | Location: Availo');
INSERT INTO Service (Name) VALUES ('Test: ICMP Ping - varnish-01.lon.aptoma.no - Location: LON');
INSERT INTO Service (Name) VALUES ('Test: ICMP Ping - varnish-02.lon.aptoma.no - Location: LON');
INSERT INTO Service (Name) VALUES ('Test: ICMP Ping | Service: DrFront MySQL Replication Slave | Location: Rackspace UK');
INSERT INTO Service (Name) VALUES ('Test: Apache port 80 | Services: DrMobile | Location: Rackspace LON');
INSERT INTO Service (Name) VALUES ('Test: ICMP Ping - Services: DrMobile - Location: Rackspace LON');
INSERT INTO Service (Name) VALUES ('DrLib');
INSERT INTO Service (Name) VALUES ('Test: Apache port 80 - Services: Select Star Blog - Location: Rackspace LON');
INSERT INTO Service (Name) VALUES ('Test: ICMP Ping - drv-videodata-prod-01.ams.aptoma.no - Location: AMS');
INSERT INTO Service (Name) VALUES ('Test: ICMP Ping - Service: DrVideo Varnish and Upload - Location: M323');
INSERT INTO Service (Name) VALUES ('Test: Apache port 8080 - DrVideo HTTP Upload - Location: M323');
INSERT INTO Service (Name) VALUES ('Test: TCP connect port 80 | Services: Varnish for DrVideo applications | Location: M323');
INSERT INTO Service (Name) VALUES ('DrLib Afton Sync Status');
INSERT INTO Service (Name) VALUES ('DrVideo Encoding - Files completed last hour');
INSERT INTO Service (Name) VALUES ('DrVideo Encoding - Files failed last hour');
INSERT INTO Service (Name) VALUES ('Test: ICMP Ping - drv-vtc-slave-13.a55.aptoma.no');
INSERT INTO Service (Name) VALUES ('Test: ICMP Ping - drv-vtc-slave-12.a55.aptoma.no');
INSERT INTO Service (Name) VALUES ('DrVideo DrKlikk Videoplays last minute');
INSERT INTO Service (Name) VALUES ('Test: Apache port 80 - Services: Custom Frontends - Location: Softlayer AMS');
INSERT INTO Service (Name) VALUES ('DrVideo Videodata API');
INSERT INTO Service (Name) VALUES ('Test: ICMP Ping - nagios.sth-p.aptoma.no');
INSERT INTO Service (Name) VALUES ('Atika Backoffice');
